openapi: 3.0.0
info:
  title: multipart test schema
  version: "1"
paths:
  /file:
    post:
      operationId: upload
      requestBody:
        content:
          "multipart/form-data":
            schema:
              type: object
              properties:
                id:
                  type: integer
                file:
                  type: string
                  format: binary
                fileArr:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        "200":
          description: "OK"
