openapi: 3.0.3
info:
 title: test
 version: '1'
paths:
 /testService/testOper:
  get:
   responses:
    '200':
     description: 'test'
     content:
      application/json:
       schema:
        $ref: '#/components/schemas/TestOperResponse'
components:
 schemas:
  TestOperResponse:
   type: object
   properties:
    id:
     type: integer
     format: int32
     nullable: true
   additionalProperties: false